// 1. 📦 QUAND UN CLIENT PASSE COMMANDE (Arrivage)
const DISCORD_WEBHOOK_NOUVELLE_COMMANDE = "aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQ2MTA1OTMzMzM2MTIzODEwNy9BNHcxYnNKWlJoLVRCMEdwQkVfWHV2TW9QYVE5dzlTNFBvVlZoOWgwOThYTnRJOU01RXJkZlpFeFNELUVzZHFsc29Wbwo=";

// 2. 👮 QUAND UN EMPLOYÉ PREND EN CHARGE (Prise de service/commande)
const DISCORD_WEBHOOK_PRISE_COMMANDE = "aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQ2MTA1OTc3NTA1OTA3MTA4MC9PcHIxLVVLUTR4SzBDYnhYOWtxVWswOGRsSzBOa3E5NENBaEl6VW9hcG9OYmg3OG9oaFVVQ0RjaHVOdk1IcTRhWGVrag==";

// 3. 📊 POUR LES RAPPORTS (Hebdo, Journalier, Mensuel)
const DISCORD_WEBHOOK_RAPPORTS = "aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQ2MTA1OTk3OTkyNTUyMDY0Mi83b3A0ZTNiVXMzSkZMUGs4cmU3SllpOWFRS004WTAwWGNGSTdONXlncnBxd3AxNjZjTkljRFZXNzFiSHgza0s0X0wyZQ==";

// 4. 📩 POUR LE FORMULAIRE DE CONTACT (Et autres notifications)
const DISCORD_WEBHOOK_AUTRE = "aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTQ2MTA2MDA5MDc1MTg4MTM4Mi9ENXpNVm03c2hYTzYzd2FXZVdsVURaUEpoRktZbGhpWTFfY25Xc1VYUk1wb3dpQXJybnhzZGtVZ09UWTVjUFRMckM3NA==";
